language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.3.3" ]; then composer config disable-tls true; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.3.3" ]; then composer config secure-http false; fi
  - composer install --no-interaction --prefer-source

script:
  - ant phplint
  - ant phpcs
  - ant phpunit
