language: php

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ant phplint
  - ant phpcs
  - ant phpunit
